name: 論文の要約作成

on:
  issues:
    types: [opened]

jobs:
  summarize_issue:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: チェックアウト
        uses: actions/checkout@v2

      # Pythonのセットアップ
      - name: Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 依存関係のインストール
      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      # スクリプトの実行
      - name: スクリプトの実行
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number || '0' }}
        run: python .github/scripts/issue_summarizer.py

# ---------------
# debug code
#
# act -W .github/workflows/issue_summarizer.yml -e event.json --env-file .env
