name: 論文のIssue作成

on:
  push:
    paths:
      - 'papers.json'  # papers.jsonが更新されたときにトリガー
  workflow_dispatch:  # 手動実行のオプション
  schedule:
    - cron: '0 15 * * 1-5'  # 平日（月曜から金曜）の毎日0時（UTC）に実行

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v2

    - name: Pythonのセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements.txt

    - name: Issue作成スクリプトの実行
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YOUR_PERSONAL_ACCESS_TOKEN_YUKIHIKO: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN_YUKIHIKO }}
      run: python .github/scripts/issue_creator.py

# ---------------
# debug code
#
# act workflow_dispatch -W .github/workflows/issue_creator.yml --env-file .env --secret-file .env -v
